export interface Review {
  id: string;
  author: string;
  rating: 1 | 2 | 3 | 4 | 5;
  text: string;
  date: string;
  localGuide?: boolean;
  reviewCount?: number;
}

// Vrais avis Google
export const reviews: Review[] = [
  {
    id: "1",
    author: "Djo",
    rating: 5,
    text: "C'est la première fois que je vais chez le dentiste et que je n'ai pas mal en sortant, un professionnel qui explique ce qu'il est entrain de faire et qui prend soin de demander à chaque manipulation si tout va bien. Merci pour tout",
    date: "Il y a 2 jours",
    reviewCount: 4,
  },
  {
    id: "2",
    author: "Fares Toumi",
    rating: 5,
    text: "Excellente expérience. Le docteur Samy Barek fait preuve d'un grand professionnalisme et d'une attention remarquable envers ses patients. Le résultat est à la hauteur de mes attentes, je recommande ce cabinet les yeux fermés.",
    date: "Il y a 2 semaines",
    reviewCount: 2,
  },
  {
    id: "3",
    author: "Zine-Ed-dine Bourak",
    rating: 5,
    text: "Très bonne expérience avec le Docteur Barek pour la pose de deux couronnes. Il m'a bien expliqué chaque étape des soins et surtout : zéro douleur ! Je recommande à 100 %",
    date: "Il y a 3 mois",
    localGuide: true,
    reviewCount: 20,
  },
  {
    id: "4",
    author: "Nabila Beldjilali",
    rating: 5,
    text: "Une perle rare de dentiste ! Chaque visite est une expérience positive. Non seulement le travail est impeccable, mais l'équipe est aussi incroyablement gentille et rassurante. Si vous cherchez un dentiste à l'écoute, compétent et qui prend le temps.",
    date: "Il y a 4 mois",
    reviewCount: 2,
  },
  {
    id: "5",
    author: "Ndella Ndiaye",
    rating: 5,
    text: "Très professionnel et bon accueil. Merci",
    date: "Il y a 4 mois",
    reviewCount: 2,
  },
  {
    id: "6",
    author: "Laura Landu",
    rating: 5,
    text: "Docteur Barek et son assistante Andréa font un travail formidable ! Ils sont bienveillants, rassurants, à l'écoute et prennent le temps qu'il faut pour expliquer tous les soins.",
    date: "Il y a 4 mois",
    reviewCount: 4,
  },
  {
    id: "7",
    author: "Is Men",
    rating: 5,
    text: "Je souhaite remercier chaleureusement le Docteur Samy Barek pour la qualité exceptionnelle de ses soins. C'est un dentiste remarquable, à la fois très compétent, à l'écoute, accueillant et rassurant.",
    date: "Il y a 4 mois",
    reviewCount: 1,
  },
  {
    id: "8",
    author: "M Mohamad",
    rating: 5,
    text: "Il s'agit d'un praticien très professionnel, doté d'une empathie et d'une sensibilité saisissante. Pas de jugement. Juste un accompagnement de qualité. L'étude et la proposition la plus adaptée. Je n'irai plus chez un autre dentiste.",
    date: "Il y a 4 mois",
    reviewCount: 11,
  },
  {
    id: "9",
    author: "Elisa",
    rating: 5,
    text: "Je suis la patiente Hourrier... très satisfaite de mon passage pendant mon séjour chez ma sœur. Même si on est pas suivi chez eux ils nous prennent quand même en RDV !",
    date: "Il y a 4 mois",
    reviewCount: 4,
  },
  {
    id: "10",
    author: "M A",
    rating: 5,
    text: "Merci infiniment au docteur Barek pour sa gentillesse et son professionnalisme. J'ai la phobie du dentiste et je suis très contente d'avoir trouvé un dentiste avec qui je me sens rassurée. Il n'a eu que des bons diagnostics me concernant.",
    date: "Il y a 4 mois",
    reviewCount: 1,
  },
  {
    id: "11",
    author: "Belmkadem Youssef",
    rating: 5,
    text: "Je remercie chaleureusement le docteur Samy pour son grand professionnalisme, la qualité de son travail ainsi que son accueil. Il prend le temps d'expliquer chaque étape avec patience, en montrant clairement les choses.",
    date: "Il y a 4 mois",
    reviewCount: 4,
  },
  {
    id: "12",
    author: "O O",
    rating: 5,
    text: "Excellent dentiste, pour ma mère qui est très très difficile, il a su la rassurer entièrement. Très professionnel, doux patient et attentionné. Au top",
    date: "Il y a 4 mois",
    reviewCount: 1,
  },
  {
    id: "13",
    author: "Arnaud Guinandie",
    rating: 5,
    text: "Un docteur incroyable ! Il est à l'écoute de ses patients, il travaille avec douceur (je n'ai même pas senti l'anesthésie) il est fort de conseils. En bref allez chez lui !",
    date: "Il y a 4 mois",
    reviewCount: 1,
  },
  {
    id: "14",
    author: "F C B",
    rating: 5,
    text: "Je me suis rendu chez ce dentiste pour la pose d'une couronne : six mois plus tard, aucun problème à signaler. Plus récemment, j'y suis retourné pour un détartrage, qui s'est également très bien passé. C'est un praticien professionnel, à l'écoute de ses patients.",
    date: "Il y a 4 mois",
    reviewCount: 2,
  },
  {
    id: "15",
    author: "Rachid T.",
    rating: 5,
    text: "Un immense merci au Dr Barek et à toute son équipe ! Je tiens vraiment à souligner son professionnalisme, sa pédagogie et surtout sa capacité à rassurer ses patients. Il prend toujours le temps d'expliquer chaque étape.",
    date: "Il y a 4 mois",
    reviewCount: 12,
  },
  {
    id: "16",
    author: "Sihem Boo",
    rating: 5,
    text: "Un grand remerciement pour la prise en charge rapide et professionnelle lors de mon urgence dentaire. L'écoute et les explications ont été très appréciées. Grâce au Dr BAREK ma douleur a été soulagée. Je vous le recommande vivement.",
    date: "Il y a 5 mois",
    reviewCount: 3,
  },
  {
    id: "17",
    author: "Iliass Chaoui",
    rating: 5,
    text: "Je recommande vivement ce cabinet dentaire ! Le Dr BAREK est à l'écoute, très professionnel et prend vraiment le temps d'expliquer chaque étape des soins. L'accueil est toujours chaleureux. Merci pour votre excellent travail !",
    date: "Il y a 5 mois",
    reviewCount: 1,
  },
  {
    id: "18",
    author: "Nabil B",
    rating: 5,
    text: "Il m'a réconcilié avec les dentistes ! Merci pour votre professionnalisme ! Rare sont les dentistes comme lui. Très efficace et à l'écoute dans sa façon de travailler.",
    date: "Il y a 5 mois",
    reviewCount: 11,
  },
  {
    id: "19",
    author: "Louisa Bni",
    rating: 5,
    text: "Dentiste pragmatique et minutieux, je recommande",
    date: "Il y a 7 mois",
    reviewCount: 7,
  },
  {
    id: "20",
    author: "Rizlène El Yazidi",
    rating: 5,
    text: "Bienveillant et doux, le docteur Barek est très professionnel, je recommande!",
    date: "Il y a 7 mois",
    reviewCount: 2,
  },
  {
    id: "21",
    author: "Sarah Belabed",
    rating: 5,
    text: "Merci au Dr Barek très patient et professionnel! Je recommande vivement !!",
    date: "Il y a 7 mois",
    reviewCount: 3,
  },
  {
    id: "22",
    author: "Faiza L",
    rating: 5,
    text: "Super dentiste !",
    date: "Il y a 7 mois",
    reviewCount: 10,
  },
  {
    id: "23",
    author: "Ali Louup",
    rating: 5,
    text: "Merci pour votre travail, M. Barek ! Grâce à vous, je ne fais que sourire au boulot. Excellent travail!",
    date: "Il y a 8 mois",
    reviewCount: 10,
  },
  {
    id: "24",
    author: "Gary Cardona",
    rating: 5,
    text: "Merci au Dr. BAREK pour sa disponibilité et professionnalisme. Très bon praticien. Cabinet très propre.",
    date: "Il y a 8 mois",
    localGuide: true,
    reviewCount: 29,
  },
  {
    id: "25",
    author: "El Amir Ben Aoun",
    rating: 5,
    text: "Très bon travail",
    date: "Il y a 8 mois",
    reviewCount: 3,
  },
  {
    id: "26",
    author: "Diacriyaou Kanoute",
    rating: 5,
    text: "Je remercie le DR Barek et toute son équipe de m'avoir pris en charge, très professionnel et sérieux dans son travail, c'est être rassurant très satisfait.",
    date: "Il y a 9 mois",
    reviewCount: 3,
  },
  {
    id: "27",
    author: "Dacine Kebci",
    rating: 5,
    text: "Étant enceinte de 6 mois et habitant à Rouen en Normandie, une rage de dent est survenue ce week-end. Aucun dentiste dispo un samedi dans les environs et même en Île-de-France. Dr Barek a accepté immédiatement de me recevoir ce jour même.",
    date: "Il y a 9 mois",
    localGuide: true,
    reviewCount: 16,
  },
  {
    id: "28",
    author: "Mohamed",
    rating: 5,
    text: "Un très très bon et excellent dentiste. Très sympathique, professionnel et efficace dans sa manière de travailler de soigner, vraiment je le recommande. Soins de très bonnes qualités. Son assistante est tout aussi sympathique et professionnelle.",
    date: "Il y a 9 mois",
    localGuide: true,
    reviewCount: 46,
  },
  {
    id: "29",
    author: "Florent Mauger",
    rating: 5,
    text: "Je suis venu pour une urgence dentaire, je recommande le docteur Samy BAREK, c'est un professionnel compétent, pédagogue et à l'écoute du patient.",
    date: "Il y a 10 mois",
    reviewCount: 3,
  },
  {
    id: "30",
    author: "Mohammed Ghouinem",
    rating: 5,
    text: "Je recommande bonne équipe professionnelle",
    date: "Il y a 10 mois",
    localGuide: true,
    reviewCount: 22,
  },
  {
    id: "31",
    author: "Hnini Bel",
    rating: 5,
    text: "Un professionnel exceptionnel ! Le Dr Barek Samy et son équipe sont d'une grande gentillesse et très à l'écoute. Chaque visite est un vrai plaisir, même pour quelqu'un comme moi qui n'était pas fan du dentiste.",
    date: "Il y a un an",
    reviewCount: 10,
  },
  {
    id: "32",
    author: "Sami Nabti",
    rating: 5,
    text: "Moi qui a la phobie du dentiste, franchement je recommande docteur Barek à 100%, Il est à l'écoute, patient, il explique très bien, d'un professionnalisme remarquable.",
    date: "Il y a un an",
    reviewCount: 7,
  },
  {
    id: "33",
    author: "Burton-Race Naomi",
    rating: 5,
    text: "Excellent dentiste avec un matériel et des techniques de pointe. Une grande flexibilité et disponibilité. Je recommande vivement!",
    date: "Il y a un an",
    localGuide: true,
    reviewCount: 144,
  },
  {
    id: "34",
    author: "Regine Guillaume",
    rating: 5,
    text: "Très bon chirurgien dentiste à l'écoute de ses patients, très gentil ainsi que ses secrétaires je le recommande vivement",
    date: "Il y a un an",
    reviewCount: 19,
  },
  {
    id: "35",
    author: "Orely Orely",
    rating: 5,
    text: "Au top ! Je recommande à 1 000 % Il prend le temps de bien expliquer ce qu'il va faire et tout le processus. Très à l'écoute et arrangeant. Vous pouvez y aller les yeux fermés !",
    date: "Il y a un an",
    reviewCount: 7,
  },
  {
    id: "36",
    author: "Si Alami",
    rating: 5,
    text: "Excellent dentiste ! Je recommande vivement",
    date: "Il y a un an",
    reviewCount: 5,
  },
  {
    id: "37",
    author: "Mehdi T",
    rating: 5,
    text: "Excellent dentiste",
    date: "Il y a un an",
    reviewCount: 4,
  },
  {
    id: "38",
    author: "Eringer Perez",
    rating: 5,
    text: "Des soins de qualité à un tarif abordable, une équipe chaleureuse, et un dentiste qui sait ce qu'il fait. En plus, j'avais rien eu à payer grâce à leur système de tiers payant. Andrea, qui est toujours à l'écoute, a fait toute la différence. Je recommande le Dr Barek à tout le monde.",
    date: "Il y a un an",
    reviewCount: 5,
  },
  {
    id: "39",
    author: "Christophe Berche",
    rating: 5,
    text: "Très professionnel, à recommander",
    date: "Il y a un an",
    reviewCount: 14,
  },
  {
    id: "40",
    author: "Joanna Merlin",
    rating: 5,
    text: "Très bon dentiste cela fait 5ans que je suis suivie malgré mon déménagement 200 bornes je reviens au cabinet très professionnel même les assistantes très gentilles je recommande fortement.",
    date: "Il y a un an",
    reviewCount: 8,
  },
  {
    id: "41",
    author: "Awa S N'diaye",
    rating: 5,
    text: "Je recommande ce dentiste. Merci à lui d'avoir pris le temps de m'expliquer et me rediriger vers l'hôpital pour ma fracture mandibulaire. Le cabinet est propre. Je reviendrai très certainement.",
    date: "Il y a un an",
    reviewCount: 2,
  },
  {
    id: "42",
    author: "Mariam Laaghouiti",
    rating: 5,
    text: "Prenez rendez-vous les yeux fermés, Excellent chirurgien dentiste.",
    date: "Il y a un an",
    reviewCount: 2,
  },
  {
    id: "43",
    author: "Michèle Mangin",
    rating: 5,
    text: "Je tiens à remercier le Docteur Barek pour son professionnalisme et ses conseils. Rendez-vous pris en urgence suite à une infection, j'y retournerai pour mon suivi dentaire. Je recommande.",
    date: "Il y a un an",
    reviewCount: 4,
  },
  {
    id: "44",
    author: "Bounadar Tarik",
    rating: 5,
    text: "Super bon dentiste.",
    date: "Il y a un an",
    reviewCount: 1,
  },
  {
    id: "45",
    author: "Richar Marin",
    rating: 5,
    text: "Le Dr Barek est vraiment un dentiste exceptionnel. Il prend le temps de bien expliquer chaque étape, utilise des équipements modernes, et on sent qu'il se préoccupe vraiment de ses patients. Andrea, son assistante, est toujours là pour aider.",
    date: "Il y a un an",
    reviewCount: 1,
  },
  {
    id: "46",
    author: "Suzan Karabulut",
    rating: 5,
    text: "J'ai consulté le Dr Barek en juin pour une pose de couronne et j'ai été très satisfaite du résultat. Il a pris le temps de m'expliquer chaque étape, et était très sympathique, ce qui est plutôt rassurant. Je recommande ce cabinet !",
    date: "Il y a un an",
    reviewCount: 7,
  },
  {
    id: "47",
    author: "Deniz B",
    rating: 5,
    text: "J'ai été accepté par le Dr Barek en urgence dans l'heure (en week-end) pour une rage de dent alors que j'avais appelé 6 cabinets aux alentours sans succès, rien que pour ça je ne le remercierai jamais assez!",
    date: "Il y a un an",
    localGuide: true,
    reviewCount: 15,
  },
  {
    id: "48",
    author: "Ahmed Haj Othman",
    rating: 5,
    text: "Un des rares dentistes à prendre le temps de nous expliquer les soins prodigués. Merci encore pour vos conseils.",
    date: "Il y a un an",
    reviewCount: 1,
  },
  {
    id: "49",
    author: "Alia Haj Othman",
    rating: 5,
    text: "Dentiste professionnel et méticuleux. Je recommande vivement.",
    date: "Il y a un an",
    reviewCount: 3,
  },
  {
    id: "50",
    author: "Delgica Corcega",
    rating: 5,
    text: "Je stresse toujours avant d'aller chez le dentiste, mais le Dr Barek m'avait tout de suite rassuré. Il est très doux et compétent. En plus, tout a été pris en charge. Andrea, son assistante, a été d'une aide précieuse. Un grand merci !",
    date: "Il y a un an",
    reviewCount: 2,
  },
  {
    id: "51",
    author: "Ines Rivero",
    rating: 5,
    text: "Je suis vraiment satisfait des soins reçus chez le Dr Barek. En plus, j'avais pas eu à avancer d'argent grâce à leur système de tiers payant. Et un grand merci à Andrea, l'assistante, qui est toujours disponible pour répondre à toutes mes questions.",
    date: "Il y a un an",
    reviewCount: 1,
  },
  {
    id: "52",
    author: "Kylian Laurent",
    rating: 5,
    text: "Très bien accueilli prise de rendez-vous hyper rapide, le docteur Samy Barek est très professionnel je recommande fortement",
    date: "Il y a un an",
    reviewCount: 3,
  },
  {
    id: "53",
    author: "Wail Benaliouad",
    rating: 5,
    text: "Dentiste formidable! Le docteur Ait M Barek est un professionnel. Il a su faire preuve de pédagogie et il m'a rassuré tout au long de mes soins. Merci. Je recommande",
    date: "Il y a un an",
    reviewCount: 3,
  },
  {
    id: "54",
    author: "Cherine Abdel-Reheem",
    rating: 5,
    text: "Dr AITMBAREK un très bon dentiste qui prend soin de ses patients, je suis venue pour une carie je me suis faite soignée de façon très efficace et très pédagogique. Je recommande vivement!!!",
    date: "Il y a un an",
    reviewCount: 2,
  },
  {
    id: "55",
    author: "Buzzard",
    rating: 5,
    text: "Ne vous fiez pas aux faux avis. Excellent.",
    date: "Il y a un an",
    reviewCount: 2,
  },
  {
    id: "56",
    author: "Aurelie S",
    rating: 5,
    text: "Deux couronnes posées sans encombre. Très professionnel et réactif. RDV les weekends très pratiques lorsque l'on travaille en semaine. Je recommande",
    date: "Il y a un an",
    localGuide: true,
    reviewCount: 19,
  },
  {
    id: "57",
    author: "Mohamed Amine Zidani",
    rating: 5,
    text: "Je tiens vivement à remercier Docteur Barek pour son professionnalisme, ses conseils ainsi que sa bonne humeur qui permet de détendre l'atmosphère, très utile pour les anxieux du cabinet dentaire comme moi!",
    date: "Il y a un an",
    reviewCount: 6,
  },
  {
    id: "58",
    author: "Wissam Hasdi",
    rating: 5,
    text: "Très bon dentiste, merci pour tout.",
    date: "Il y a un an",
    reviewCount: 2,
  },
  {
    id: "59",
    author: "Naloufi Nabil",
    rating: 5,
    text: "J'ai été pris en urgence à la dernière minute. Je recommande",
    date: "Il y a un an",
    localGuide: true,
    reviewCount: 24,
  },
  {
    id: "60",
    author: "Nico F Seiei",
    rating: 5,
    text: "Très bon dentiste pour ma part, je suis parti pour blanchir mes dents au top.",
    date: "Il y a un an",
    reviewCount: 1,
  },
  {
    id: "61",
    author: "Senjo",
    rating: 5,
    text: "Service de haute qualité",
    date: "Il y a un an",
    reviewCount: 4,
  },
  {
    id: "62",
    author: "Kevin Burgei",
    rating: 5,
    text: "Dentiste professionnel. À l'écoute et de bon conseil, il a pris son temps pour répondre à toutes mes questions. Je recommande.",
    date: "Il y a un an",
    reviewCount: 5,
  },
  {
    id: "63",
    author: "Nabil",
    rating: 5,
    text: "Cabinet très correct j'ai été pris en charge par le Dr BAREK et je suis très content du résultat. Il a toujours pris soin de répondre au mieux à mes besoins. Un grand merci à lui.",
    date: "Il y a un an",
    reviewCount: 12,
  },
  {
    id: "64",
    author: "Mehdi Ba",
    rating: 5,
    text: "Un dentiste super disponible. Bienveillant et à l'écoute. Je le remercie infiniment pour m'avoir soigné en urgence un week-end.",
    date: "Il y a un an",
    localGuide: true,
    reviewCount: 21,
  },
  {
    id: "65",
    author: "Sahnouni Noussaiba",
    rating: 5,
    text: "Je recommande vivement ce dentiste pour son professionnalisme et sa grande gentillesse. J'ai été accueillie avec le sourire et mise à l'aise. Les explications étaient claires et le traitement s'est déroulé sans aucune douleur.",
    date: "Il y a un an",
    reviewCount: 5,
  },
  {
    id: "66",
    author: "Hugo",
    rating: 5,
    text: "Première consultation avec Samy, très sympathique et professionnel. Je reviendrai en cas de nouveaux problèmes sans hésiter !",
    date: "Il y a un an",
    reviewCount: 7,
  },
  {
    id: "67",
    author: "Amaury Martin",
    rating: 5,
    text: "Super expérience, digne de confiance !",
    date: "Il y a un an",
    reviewCount: 3,
  },
  {
    id: "68",
    author: "Sofian Coult",
    rating: 5,
    text: "Super dentiste. Efficace et sans douleur. Plusieurs années de soins pour différents sujets, jamais eu besoin d'y retourner deux fois pour la même chose. Je me déplace chaque fois depuis le 91 pour l'unique satisfaction d'avoir trouvé le bon dentiste!",
    date: "Il y a un an",
    reviewCount: 2,
  },
  {
    id: "69",
    author: "Djamal T.",
    rating: 5,
    text: "Excellent dentiste ! Le Dr Barek m'a soigné plusieurs fois et je suis toujours très satisfait. Il m'a récemment posé une couronne : le résultat est parfait, sans douleur.",
    date: "Il y a un an",
    localGuide: true,
    reviewCount: 46,
  },
];

// Stats calculées
export const reviewStats = {
  totalReviews: 139,
  averageRating: 5,
  googleUrl: "https://www.google.com/maps/place/Cabinet+Dentaire+Cergy+-+Dr+BAREK/@49.0338929,2.0745645,17z/",
  distribution: {
    5: 139,
    4: 0,
    3: 0,
    2: 0,
    1: 0,
  },
};
